# Using eget v1.3.4
# Custom keys begin with an underscore, eget should ignore unknown keys

[global]
target = "~/.local/bin"
# This must be specified here, calling eget with `--download-all --upgrade_only`
# seems to download unconditionally
upgrade_only = true

["zyedidia/eget"]

["sharkdp/bat"]
asset_filters = ["gnu"]

["eza-community/eza"]
asset_filters = ["gnu", "zip"]

["sharkdp/fd"]
asset_filters = ["gnu"]

["dandavison/delta"]
asset_filters = ["gnu"]

["junegunn/fzf"]

["ajeetdsouza/zoxide"]

["jesseduffield/lazygit"]

["neovim/neovim"]
asset_filters = ["x86"]
target = "~/.local/bin/nvim"

["astral-sh/uv"]
asset_filters = ["gnu"]
all = true
